# Server port
server.port=8080

# UAT Encryption Key - AES-256 (from PDF page 5)
simulator.encryption.key=q4UOLnbuVc0mP8Jf634f1zCGVy2pf9lj

# UAT Checksum Key - SHA-512 HMAC (from PDF page 5)
simulator.checksum.key=union@123

# Show DEBUG logs for our package only
logging.level.com.billdesk=DEBUG
logging.level.root=WARN
